- name: Vcenter user
  debug:
    msg: "Vcenter user is {{ user }}"

- name: Login into vCenter and get cookies
  uri:
    url: https://{{ vcenter_server }}/rest/com/vmware/cis/session
    force_basic_auth: yes
    validate_certs: no
    method: POST
    user: "{{ user }}"
    password: "{{ password }}"
  register: login

- name: Get all hosts from vCenter using cookies from last task
  uri:
    url: https://{{ vcenter_server }}/rest/vcenter/host
    force_basic_auth: yes
    validate_certs: no
    headers:
      Cookie: "{{ login.set_cookie }}"
  register: vchosts

- name: show vchosts
  debug:
    msg: " {{item.name}} {{item.power_state}}"
  loop: "{{ vchosts.json.value }}"

- pause:
    prompt: "Set hostname"
  register: host_name
  echo: no

- name: Gather vmware host facts from vCenter
  vmware_host_facts:
    hostname: "{{ vcenter_server }}"
    username: "{{ user }}"
    password: "{{ password }}"
    esxi_hostname: "{{ host_name }}"
    validate_certs: false
  register: host_facts

- name: show host_facts
  debug:
    msg: "host_facts are {{ host_facts.ansible_datastore | to_nice_json }}"
  when: host_facts is defined