- name: Vcenter user
  debug:
    msg: "Vcenter user is {{ user }}"

- name: Login into vCenter and get cookies
  uri:
    url: https://{{ vcenter_server }}/rest/com/vmware/cis/session
    force_basic_auth: yes
    validate_certs: no
    method: POST
    user: "{{ user }}"
    password: "{{ password }}"
    register: login