- name: search pip
  shell: pip --version
  register: pip_status
  ignore_errors: true

- name: install python-pip
  yum:
    name: python-pip
    state: latest
  register: pip_install
  when: pip_status is failed

- name: Install pyvmomi
  pip:
    name: pyvmomi
  when: 
    - pip_status is succeeded
    - pip_install is succeeded
