- name: search pip
  shell: systemctl is-active pip
  register: pip_status
  ignore_errors: true

- name: install python-pip
  yum:
    name: python-pip
    state: latest
  when: pip_status is failed

- name: Install pyvmomi
  pip:
    name: pyvmomi
  when: pip_status is succeeded
