- name: search pip
  shell: systemctl is-active pip
  register: pip_status
  ignore_errors: true

- name: install pip
  yum:
    name: pip
    state: latest
  when: ({{pip_status.stdout}} == "unknown")

- name: Install pyvmomi
  pip:
    name: pyvmomi
  when: ({{pip_status.stdout}} == "active")
